/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const BloodGroup = IDL.Variant({
  'AB_neg' : IDL.Null,
  'AB_pos' : IDL.Null,
  'B_neg' : IDL.Null,
  'B_pos' : IDL.Null,
  'A_neg' : IDL.Null,
  'A_pos' : IDL.Null,
  'O_neg' : IDL.Null,
  'O_pos' : IDL.Null,
});
export const Donor = IDL.Record({
  'contactInfo' : IDL.Text,
  'donorId' : IDL.Principal,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'bloodGroup' : BloodGroup,
  'lastDonation' : Time,
});
export const UrgencyLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Critical' : IDL.Null,
});
export const RecipientRequest = IDL.Record({
  'urgencyLevel' : UrgencyLevel,
  'requestId' : IDL.Principal,
  'area' : IDL.Text,
  'requiredBloodGroup' : BloodGroup,
  'timestamp' : Time,
  'patientName' : IDL.Text,
  'hospitalName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DonorInput = IDL.Record({
  'contactInfo' : IDL.Text,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'bloodGroup' : BloodGroup,
});
export const RecipientRequestInput = IDL.Record({
  'urgencyLevel' : UrgencyLevel,
  'area' : IDL.Text,
  'requiredBloodGroup' : BloodGroup,
  'patientName' : IDL.Text,
  'hospitalName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getAllRecipientRequests' : IDL.Func(
      [],
      [IDL.Vec(RecipientRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonorById' : IDL.Func([IDL.Principal], [IDL.Opt(Donor)], ['query']),
  'getRecipientRequestById' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(RecipientRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerDonor' : IDL.Func([DonorInput], [], []),
  'registerRecipientRequest' : IDL.Func([RecipientRequestInput], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDonorsByBloodGroupAndArea' : IDL.Func(
      [BloodGroup, IDL.Text],
      [IDL.Vec(Donor)],
      ['query'],
    ),
  'searchRecipientRequestsByBloodGroupAndArea' : IDL.Func(
      [BloodGroup, IDL.Text],
      [IDL.Vec(RecipientRequest)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const BloodGroup = IDL.Variant({
    'AB_neg' : IDL.Null,
    'AB_pos' : IDL.Null,
    'B_neg' : IDL.Null,
    'B_pos' : IDL.Null,
    'A_neg' : IDL.Null,
    'A_pos' : IDL.Null,
    'O_neg' : IDL.Null,
    'O_pos' : IDL.Null,
  });
  const Donor = IDL.Record({
    'contactInfo' : IDL.Text,
    'donorId' : IDL.Principal,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'bloodGroup' : BloodGroup,
    'lastDonation' : Time,
  });
  const UrgencyLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Critical' : IDL.Null,
  });
  const RecipientRequest = IDL.Record({
    'urgencyLevel' : UrgencyLevel,
    'requestId' : IDL.Principal,
    'area' : IDL.Text,
    'requiredBloodGroup' : BloodGroup,
    'timestamp' : Time,
    'patientName' : IDL.Text,
    'hospitalName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DonorInput = IDL.Record({
    'contactInfo' : IDL.Text,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'bloodGroup' : BloodGroup,
  });
  const RecipientRequestInput = IDL.Record({
    'urgencyLevel' : UrgencyLevel,
    'area' : IDL.Text,
    'requiredBloodGroup' : BloodGroup,
    'patientName' : IDL.Text,
    'hospitalName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
    'getAllRecipientRequests' : IDL.Func(
        [],
        [IDL.Vec(RecipientRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonorById' : IDL.Func([IDL.Principal], [IDL.Opt(Donor)], ['query']),
    'getRecipientRequestById' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(RecipientRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerDonor' : IDL.Func([DonorInput], [], []),
    'registerRecipientRequest' : IDL.Func([RecipientRequestInput], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDonorsByBloodGroupAndArea' : IDL.Func(
        [BloodGroup, IDL.Text],
        [IDL.Vec(Donor)],
        ['query'],
      ),
    'searchRecipientRequestsByBloodGroupAndArea' : IDL.Func(
        [BloodGroup, IDL.Text],
        [IDL.Vec(RecipientRequest)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };