/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BloodGroup = { 'AB_neg' : null } |
  { 'AB_pos' : null } |
  { 'B_neg' : null } |
  { 'B_pos' : null } |
  { 'A_neg' : null } |
  { 'A_pos' : null } |
  { 'O_neg' : null } |
  { 'O_pos' : null };
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Donor {
  'contactInfo' : string,
  'donorId' : Principal,
  'area' : string,
  'name' : string,
  'bloodGroup' : BloodGroup,
  'lastDonation' : Time,
}
export interface DonorInput {
  'contactInfo' : string,
  'area' : string,
  'name' : string,
  'bloodGroup' : BloodGroup,
}
export interface RecipientRequest {
  'urgencyLevel' : UrgencyLevel,
  'requestId' : Principal,
  'area' : string,
  'requiredBloodGroup' : BloodGroup,
  'timestamp' : Time,
  'patientName' : string,
  'hospitalName' : string,
}
export interface RecipientRequestInput {
  'urgencyLevel' : UrgencyLevel,
  'area' : string,
  'requiredBloodGroup' : BloodGroup,
  'patientName' : string,
  'hospitalName' : string,
}
export type Time = bigint;
export type UrgencyLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Critical' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllDonors' : ActorMethod<[], Array<Donor>>,
  'getAllRecipientRequests' : ActorMethod<[], Array<RecipientRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonorById' : ActorMethod<[Principal], [] | [Donor]>,
  'getRecipientRequestById' : ActorMethod<[Principal], [] | [RecipientRequest]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerDonor' : ActorMethod<[DonorInput], undefined>,
  'registerRecipientRequest' : ActorMethod<[RecipientRequestInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDonorsByBloodGroupAndArea' : ActorMethod<
    [BloodGroup, string],
    Array<Donor>
  >,
  'searchRecipientRequestsByBloodGroupAndArea' : ActorMethod<
    [BloodGroup, string],
    Array<RecipientRequest>
  >,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];