/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Donor {
    contactInfo: string;
    donorId: Principal;
    area: string;
    name: string;
    bloodGroup: BloodGroup;
    lastDonation: Time;
}
export interface ContactSubmission {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface RecipientRequest {
    urgencyLevel: UrgencyLevel;
    requestId: Principal;
    area: string;
    requiredBloodGroup: BloodGroup;
    timestamp: Time;
    patientName: string;
    hospitalName: string;
}
export interface DonorInput {
    contactInfo: string;
    area: string;
    name: string;
    bloodGroup: BloodGroup;
}
export interface RecipientRequestInput {
    urgencyLevel: UrgencyLevel;
    area: string;
    requiredBloodGroup: BloodGroup;
    patientName: string;
    hospitalName: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export enum BloodGroup {
    AB_neg = "AB_neg",
    AB_pos = "AB_pos",
    B_neg = "B_neg",
    B_pos = "B_pos",
    A_neg = "A_neg",
    A_pos = "A_pos",
    O_neg = "O_neg",
    O_pos = "O_pos"
}
export enum UrgencyLevel {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Critical = "Critical"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllContactSubmissions(): Promise<Array<ContactSubmission>>;
    getAllDonors(): Promise<Array<Donor>>;
    getAllRecipientRequests(): Promise<Array<RecipientRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDonorById(donorId: Principal): Promise<Donor | null>;
    getRecipientRequestById(requestId: Principal): Promise<RecipientRequest | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerDonor(input: DonorInput): Promise<void>;
    registerRecipientRequest(input: RecipientRequestInput): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchDonorsByBloodGroupAndArea(bloodGroup: BloodGroup, area: string): Promise<Array<Donor>>;
    searchRecipientRequestsByBloodGroupAndArea(bloodGroup: BloodGroup, area: string): Promise<Array<RecipientRequest>>;
    submitContactForm(name: string, email: string, message: string): Promise<void>;
    getPendingDonors(): Promise<Array<Donor>>;
    getPendingRecipientRequests(): Promise<Array<RecipientRequest>>;
    approveDonor(donorId: Principal): Promise<boolean>;
    rejectDonor(donorId: Principal): Promise<boolean>;
    approveRecipientRequest(requestId: Principal): Promise<boolean>;
    rejectRecipientRequest(requestId: Principal): Promise<boolean>;
    deleteDonor(donorId: Principal): Promise<boolean>;
    deleteRecipientRequest(requestId: Principal): Promise<boolean>;
    updateDonor(donorId: Principal, input: DonorInput): Promise<boolean>;
    updateRecipientRequest(requestId: Principal, input: RecipientRequestInput): Promise<boolean>;
}
import type { BloodGroup as _BloodGroup, Donor as _Donor, DonorInput as _DonorInput, RecipientRequest as _RecipientRequest, RecipientRequestInput as _RecipientRequestInput, Time as _Time, UrgencyLevel as _UrgencyLevel, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactSubmissions();
            return result;
        }
    }
    async getAllDonors(): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonors();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonors();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRecipientRequests(): Promise<Array<RecipientRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecipientRequests();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecipientRequests();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorById(arg0: Principal): Promise<Donor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipientRequestById(arg0: Principal): Promise<RecipientRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipientRequestById(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipientRequestById(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerDonor(arg0: DonorInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDonor(to_candid_DonorInput_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDonor(to_candid_DonorInput_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async registerRecipientRequest(arg0: RecipientRequestInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRecipientRequest(to_candid_RecipientRequestInput_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRecipientRequest(to_candid_RecipientRequestInput_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchDonorsByBloodGroupAndArea(arg0: BloodGroup, arg1: string): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDonorsByBloodGroupAndArea(to_candid_BloodGroup_n20(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDonorsByBloodGroupAndArea(to_candid_BloodGroup_n20(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchRecipientRequestsByBloodGroupAndArea(arg0: BloodGroup, arg1: string): Promise<Array<RecipientRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRecipientRequestsByBloodGroupAndArea(to_candid_BloodGroup_n20(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRecipientRequestsByBloodGroupAndArea(to_candid_BloodGroup_n20(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async getPendingDonors(): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getPendingDonors();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await (this.actor as any).getPendingDonors();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingRecipientRequests(): Promise<Array<RecipientRequest>> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).getPendingRecipientRequests();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else {
            const result = await (this.actor as any).getPendingRecipientRequests();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveDonor(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try { return await (this.actor as any).approveDonor(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await (this.actor as any).approveDonor(arg0); }
    }
    async rejectDonor(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try { return await (this.actor as any).rejectDonor(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await (this.actor as any).rejectDonor(arg0); }
    }
    async approveRecipientRequest(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try { return await (this.actor as any).approveRecipientRequest(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await (this.actor as any).approveRecipientRequest(arg0); }
    }
    async rejectRecipientRequest(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try { return await (this.actor as any).rejectRecipientRequest(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await (this.actor as any).rejectRecipientRequest(arg0); }
    }
    async deleteDonor(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try { return await (this.actor as any).deleteDonor(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await (this.actor as any).deleteDonor(arg0); }
    }
    async deleteRecipientRequest(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try { return await (this.actor as any).deleteRecipientRequest(arg0); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await (this.actor as any).deleteRecipientRequest(arg0); }
    }
    async updateDonor(arg0: Principal, arg1: DonorInput): Promise<boolean> {
        if (this.processError) {
            try { return await (this.actor as any).updateDonor(arg0, to_candid_DonorInput_n18(this._uploadFile, this._downloadFile, arg1)); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await (this.actor as any).updateDonor(arg0, to_candid_DonorInput_n18(this._uploadFile, this._downloadFile, arg1)); }
    }
    async updateRecipientRequest(arg0: Principal, arg1: RecipientRequestInput): Promise<boolean> {
        if (this.processError) {
            try { return await (this.actor as any).updateRecipientRequest(arg0, to_candid_RecipientRequestInput_n22(this._uploadFile, this._downloadFile, arg1)); }
            catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { return await (this.actor as any).updateRecipientRequest(arg0, to_candid_RecipientRequestInput_n22(this._uploadFile, this._downloadFile, arg1)); }
    }
}
function from_candid_BloodGroup_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Donor_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donor): Donor {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_RecipientRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecipientRequest): RecipientRequest {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UrgencyLevel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UrgencyLevel): UrgencyLevel {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donor]): Donor | null {
    return value.length === 0 ? null : from_candid_Donor_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RecipientRequest]): RecipientRequest | null {
    return value.length === 0 ? null : from_candid_RecipientRequest_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    urgencyLevel: _UrgencyLevel;
    requestId: Principal;
    area: string;
    requiredBloodGroup: _BloodGroup;
    timestamp: _Time;
    patientName: string;
    hospitalName: string;
}): {
    urgencyLevel: UrgencyLevel;
    requestId: Principal;
    area: string;
    requiredBloodGroup: BloodGroup;
    timestamp: Time;
    patientName: string;
    hospitalName: string;
} {
    return {
        urgencyLevel: from_candid_UrgencyLevel_n11(_uploadFile, _downloadFile, value.urgencyLevel),
        requestId: value.requestId,
        area: value.area,
        requiredBloodGroup: from_candid_BloodGroup_n6(_uploadFile, _downloadFile, value.requiredBloodGroup),
        timestamp: value.timestamp,
        patientName: value.patientName,
        hospitalName: value.hospitalName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    donorId: Principal;
    area: string;
    name: string;
    bloodGroup: _BloodGroup;
    lastDonation: _Time;
}): {
    contactInfo: string;
    donorId: Principal;
    area: string;
    name: string;
    bloodGroup: BloodGroup;
    lastDonation: Time;
} {
    return {
        contactInfo: value.contactInfo,
        donorId: value.donorId,
        area: value.area,
        name: value.name,
        bloodGroup: from_candid_BloodGroup_n6(_uploadFile, _downloadFile, value.bloodGroup),
        lastDonation: value.lastDonation
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
}): UrgencyLevel {
    return "Low" in value ? UrgencyLevel.Low : "High" in value ? UrgencyLevel.High : "Medium" in value ? UrgencyLevel.Medium : "Critical" in value ? UrgencyLevel.Critical : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AB_neg: null;
} | {
    AB_pos: null;
} | {
    B_neg: null;
} | {
    B_pos: null;
} | {
    A_neg: null;
} | {
    A_pos: null;
} | {
    O_neg: null;
} | {
    O_pos: null;
}): BloodGroup {
    return "AB_neg" in value ? BloodGroup.AB_neg : "AB_pos" in value ? BloodGroup.AB_pos : "B_neg" in value ? BloodGroup.B_neg : "B_pos" in value ? BloodGroup.B_pos : "A_neg" in value ? BloodGroup.A_neg : "A_pos" in value ? BloodGroup.A_pos : "O_neg" in value ? BloodGroup.O_neg : "O_pos" in value ? BloodGroup.O_pos : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donor>): Array<Donor> {
    return value.map((x)=>from_candid_Donor_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecipientRequest>): Array<RecipientRequest> {
    return value.map((x)=>from_candid_RecipientRequest_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BloodGroup_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_DonorInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DonorInput): _DonorInput {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_RecipientRequestInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipientRequestInput): _RecipientRequestInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UrgencyLevel_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrgencyLevel): _UrgencyLevel {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    area: string;
    name: string;
    bloodGroup: BloodGroup;
}): {
    contactInfo: string;
    area: string;
    name: string;
    bloodGroup: _BloodGroup;
} {
    return {
        contactInfo: value.contactInfo,
        area: value.area,
        name: value.name,
        bloodGroup: to_candid_BloodGroup_n20(_uploadFile, _downloadFile, value.bloodGroup)
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    urgencyLevel: UrgencyLevel;
    area: string;
    requiredBloodGroup: BloodGroup;
    patientName: string;
    hospitalName: string;
}): {
    urgencyLevel: _UrgencyLevel;
    area: string;
    requiredBloodGroup: _BloodGroup;
    patientName: string;
    hospitalName: string;
} {
    return {
        urgencyLevel: to_candid_UrgencyLevel_n24(_uploadFile, _downloadFile, value.urgencyLevel),
        area: value.area,
        requiredBloodGroup: to_candid_BloodGroup_n20(_uploadFile, _downloadFile, value.requiredBloodGroup),
        patientName: value.patientName,
        hospitalName: value.hospitalName
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    AB_neg: null;
} | {
    AB_pos: null;
} | {
    B_neg: null;
} | {
    B_pos: null;
} | {
    A_neg: null;
} | {
    A_pos: null;
} | {
    O_neg: null;
} | {
    O_pos: null;
} {
    return value == BloodGroup.AB_neg ? {
        AB_neg: null
    } : value == BloodGroup.AB_pos ? {
        AB_pos: null
    } : value == BloodGroup.B_neg ? {
        B_neg: null
    } : value == BloodGroup.B_pos ? {
        B_pos: null
    } : value == BloodGroup.A_neg ? {
        A_neg: null
    } : value == BloodGroup.A_pos ? {
        A_pos: null
    } : value == BloodGroup.O_neg ? {
        O_neg: null
    } : value == BloodGroup.O_pos ? {
        O_pos: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UrgencyLevel): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Critical: null;
} {
    return value == UrgencyLevel.Low ? {
        Low: null
    } : value == UrgencyLevel.High ? {
        High: null
    } : value == UrgencyLevel.Medium ? {
        Medium: null
    } : value == UrgencyLevel.Critical ? {
        Critical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
